import { Permissions } from "src/app/services/permissions.service";
import { RouteInfo } from "./sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "Tableau de bord",
    icon: "fas fa-tachometer-alt",
    class: "menu-toggle",
    roles: [
      Permissions.PermissionsEnum.SuperAdmin,
      Permissions.PermissionsEnum.ViewDashboard,
    ],
    submenu: [
      {
        path: "/dashboard/main",
        title: "Tableau de bord",
        icon: "",
        class: "ml-menu",
        roles: [
          Permissions.PermissionsEnum.SuperAdmin,
          Permissions.PermissionsEnum.ViewDashboard,
        ],
        submenu: [],
      },
      {
        path: "/dashboard/request-log",
        title: "Log",
        icon: "",
        class: "ml-menu",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Utilisateurs",
    icon: "fas fa-users",
    class: "menu-toggle",
    roles: [Permissions.PermissionsEnum.SuperAdmin],
    submenu: [
      {
        path: "/membership/roles/role-list",
        title: "Roles",
        icon: "",
        class: "ml-menu",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        submenu: [],
      },
      {
        path: "/membership/users/user-list",
        title: "Utilisateurs",
        icon: "",
        class: "ml-menu",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Référenciel",
    icon: "fas fa-list",
    class: "menu-toggle",
    roles: [
      Permissions.PermissionsEnum.RefProdEditQuota,
      Permissions.PermissionsEnum.RefProdListing,
    ],
    submenu: [
      {
        path: "/product/product-list",
        title: "Produits",
        icon: "",
        class: "ml-menu",
        roles: [
          Permissions.PermissionsEnum.RefProdEditQuota,
          Permissions.PermissionsEnum.RefProdListing,
        ],
        submenu: [],
      },
      {
        path: "/product-class/product-class-list",
        title: "Classes de produits",
        icon: "",
        class: "ml-menu",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        submenu: [],
      },

      {
        path: "/brand/brand-list",
        title: "Marques",
        icon: "",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/therapeutic-class/therapeutic-class-list",
        title: "Classes thérapeutiques",
        icon: "",
        class: "ml-menu",
        submenu: [],
        roles: [Permissions.PermissionsEnum.SuperAdmin],
      },
      {
        path: "/pharmacological-class/pharmacological-class-list",
        title: "Classes pharmaco",
        icon: "",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/manufacturer/manufacturer-list",
        title: "Fabricants",
        icon: "",
        class: "ml-menu",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        submenu: [],
      },
      {
        path: "/tax-group/tax-group-list",
        title: "Groupes de Taxes",
        icon: "",
        class: "ml-menu",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        submenu: [],
      },
      {
        path: "/form/form-list",
        title: "Formes",
        icon: "",
        class: "ml-menu",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        submenu: [],
      },
      {
        path: "/dosage/dosage-list",
        title: "Dosages",
        icon: "",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/packaging/packaging-list",
        title: "Emballage",
        icon: "",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/lists/lists-list",
        title: "Listes",
        icon: "",
        class: "ml-menu",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        submenu: [],
      },
      {
        path: "/dci/dci-list",
        title: "DCI",
        icon: "",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/dci-code/dci-code-list",
        title: "Code DCI",
        icon: "",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/picking-zone/picking-zone-list",
        title: "Zones de préparation",
        icon: "",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/zone-group/zone-group-list",
        title: "Groupe de Zones",
        icon: "",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/transaction-type/transaction-type-list",
        title: "Type de transactions",
        icon: "",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/stock-state/stock-state-list",
        title: "Statut Stock",
        icon: "",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Tiers",
    icon: "fas fa-building",
    class: "menu-toggle",
    roles: [
      Permissions.PermissionsEnum.SuperAdmin,
      Permissions.PermissionsEnum.TierClientBlock,
      Permissions.PermissionsEnum.TierClientListing,
    ],
    submenu: [
      {
        path: "/tiers/customer/customer-list",
        title: "Organisations",
        icon: "",
        class: "ml-menu",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        submenu: [],
      },

      {
        path: "/tiers/client/client-list",
        title: "Clients",
        icon: "",
        roles: [
          Permissions.PermissionsEnum.SuperAdmin,
          Permissions.PermissionsEnum.TierClientBlock,
          Permissions.PermissionsEnum.TierClientListing,
        ],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/tiers/supplier/supplier-list",
        title: "Fournisseurs",
        icon: "",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/tiers/sector-client/sector-list",
        title: "Secteurs",
        icon: "",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: " Achat",
    icon: "fas fa-box-open",
    class: "menu-toggle",
    roles: [Permissions.PermissionsEnum.SuperAdmin],
    submenu: [
      {
        path: "/procurment/supplier-orders-list",
        title: "Commandes Fournisseurs",
        icon: "fas fa-shopping-cart",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/procurment/supplier-invoices-list",
        title: "Factures Fournisseurs",
        icon: "fas fa-shopping-cart",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/procurment/delivery-receipt-list",
        title: "Bons de Receptions",
        icon: "fas fa-shopping-cart",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Stocks",
    icon: "fas fa-pallet",
    class: "menu-toggle",
    roles: [
      Permissions.PermissionsEnum.SuperAdmin,
      Permissions.PermissionsEnum.StockAvailableListing,
      Permissions.PermissionsEnum.StockReservedQuantityListing,
    ],
    submenu: [
      {
        path: "/inventory/invent/invent-list",
        title: "Stock",
        icon: "",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/inventory/inventsum/inventsum-list",
        title: "Disponible",
        icon: "",
        roles: [
          Permissions.PermissionsEnum.SuperAdmin,
          Permissions.PermissionsEnum.StockAvailableListing,
        ],
        class: "ml-menu",
        submenu: [],
      },

      {
        path: "/inventory/batch/batch-list",
        title: "Lots",
        icon: "",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/inventory/inventsum/transaction-listing",
        title: "Transactions Stock",
        icon: "",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/inventory/transfer-log/transfer-log-list",
        title: "Journal de transfert",
        icon: "",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/inventory/inventsum/arrival-list",
        title: "Arrivage",
        icon: "",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/inventory/inventsum/reseved-qnt-list",
        title: "Quantités réservées",
        icon: "",
        roles: [
          Permissions.PermissionsEnum.SuperAdmin,
          Permissions.PermissionsEnum.StockReservedQuantityListing,
        ],
        class: "ml-menu",
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "Ventes",
    icon: "fas fa-shopping-cart",
    class: "menu-toggle",
    roles: [
      Permissions.PermissionsEnum.SuperAdmin,
      Permissions.PermissionsEnum.OrdersOrdersCreate,
      Permissions.PermissionsEnum.OrdersOrdersListing,
      Permissions.PermissionsEnum.OrdersProformatOrdersDelete,
      Permissions.PermissionsEnum.OrdersProformatOrdersListing,
      Permissions.PermissionsEnum.OrdersTradeAgreementListing,
      Permissions.PermissionsEnum.OrdersInvoicesListing,
    ],
    submenu: [
      {
        path: "/sales/sales-person-orders",
        title: "Commandes",
        icon: "fas fa-shopping-cart",
        roles: [
          Permissions.PermissionsEnum.SuperAdmin,
          Permissions.PermissionsEnum.OrdersOrdersCreate,
          Permissions.PermissionsEnum.OrdersOrdersListing,
        ],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/sales/all-pending-orders",
        title: "Commandes en attente",
        icon: "fas fa-shopping-cart",
        roles: [
          Permissions.PermissionsEnum.SuperAdmin,
          Permissions.PermissionsEnum.OrdersProformatOrdersDelete,
          Permissions.PermissionsEnum.OrdersProformatOrdersListing,
        ],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/discounts/discount-list",
        title: "Accords Commerciaux",
        icon: "fas fa-percent",
        roles: [
          Permissions.PermissionsEnum.SuperAdmin,
          Permissions.PermissionsEnum.OrdersTradeAgreementListing,
        ],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/billing/invoices-list",
        title: "Factures Ventes",
        icon: "fas fa-percent",
        roles: [
          Permissions.PermissionsEnum.SuperAdmin,
          Permissions.PermissionsEnum.OrdersInvoicesListing,
        ],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/billing/financial-trans-list",
        title: "Transactions Financières",
        icon: "fas fa-percent",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/customer-credit/customer-credit-list",
        title: "Avoirs Client",
        icon: "fas fa-percent",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Arrivage",
    icon: "fas fa-box-open",
    class: "menu-toggle",
    roles: [
      Permissions.PermissionsEnum.SuperAdmin,
      Permissions.PermissionsEnum.QuotasSentDemandsListing,
      Permissions.PermissionsEnum.QuotasSentDemandsCreate,
      Permissions.PermissionsEnum.QuotasReceivedDemandsListing,
      Permissions.PermissionsEnum.QuotasReceivedDemandsManage,
      Permissions.PermissionsEnum.QuotasDistributionCreate,
      Permissions.PermissionsEnum.QuotasDistributionDelete,
      Permissions.PermissionsEnum.QuotasDistributionListing,
      Permissions.PermissionsEnum.QuotasDistributionUpdate,
      Permissions.PermissionsEnum.QuotasReportsView,
      Permissions.PermissionsEnum.QuotasProductsAvailable,
    ],
    submenu: [
      {
        path: "/quotas/quota-list",
        title: "Distribution des arrivages",
        icon: "fas fa-shopping-cart",
        roles: [
          Permissions.PermissionsEnum.SuperAdmin,
          Permissions.PermissionsEnum.QuotasDistributionCreate,
          Permissions.PermissionsEnum.QuotasDistributionDelete,
          Permissions.PermissionsEnum.QuotasDistributionListing,
          Permissions.PermissionsEnum.QuotasDistributionUpdate,
        ],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/quotas/quota-request-list",
        title: "Demande arrivage",
        icon: "fas fa-shopping-cart",
        roles: [
          Permissions.PermissionsEnum.SuperAdmin,
          Permissions.PermissionsEnum.QuotasSentDemandsListing,
          Permissions.PermissionsEnum.QuotasSentDemandsCreate,
          Permissions.PermissionsEnum.QuotasReceivedDemandsListing,
          Permissions.PermissionsEnum.QuotasReceivedDemandsManage,
        ],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/quotas/quota-received-list",
        title: "Demandes reçues",
        icon: "fas fa-shopping-cart",
        roles: [
          Permissions.PermissionsEnum.SuperAdmin,
          Permissions.PermissionsEnum.QuotasReceivedDemandsListing,
          Permissions.PermissionsEnum.QuotasReceivedDemandsManage,
        ],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/quotas/available-qnt-list",
        title: "Produits disponible",
        icon: "fas fa-shopping-cart",
        roles: [
          Permissions.PermissionsEnum.SuperAdmin,
          Permissions.PermissionsEnum.QuotasProductsAvailable,
        ],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/quotas/supervisor-transfer-list",
        title: "Réaffectation des clients",
        icon: "fas fa-shopping-cart",
        roles: [Permissions.PermissionsEnum.SuperAdmin, Permissions.PermissionsEnum.QuotasCustomerAssignmentView],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/quotas/ssrs-report",
        title: "Rapport arrivage",
        icon: "fas fa-shopping-cart",
        roles: [
          Permissions.PermissionsEnum.SuperAdmin,
          Permissions.PermissionsEnum.QuotasReportsView,
        ],
        class: "ml-menu",
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "rh",
    icon: "fas fa-id-card-alt",
    class: "menu-toggle",
    roles: [Permissions.PermissionsEnum.SuperAdmin],
    submenu: [
      {
        path: "/rh/employee-list",
        title: "Liste employees",
        icon: "fas fa-shopping-cart",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Ordre de préparations",
    icon: "fas fa-boxes	",
    class: "menu-toggle",
    roles: [
      Permissions.PermissionsEnum.SuperAdmin,
      Permissions.PermissionsEnum.OrderPreparationPrinting,
      Permissions.PermissionsEnum.OrderPreparationControl,
      Permissions.PermissionsEnum.OrderPreparationConsolidation,
      Permissions.PermissionsEnum.OrderPreparationExpedition,
      Permissions.PermissionsEnum.OrderPreparationArchive,
    ],
    submenu: [
      {
        path: "/preparation-orders/preparation-orders-list",
        title: "Impression",
        icon: "fas fa-shopping-cart",
        roles: [
          Permissions.PermissionsEnum.SuperAdmin,
          Permissions.PermissionsEnum.OrderPreparationPrinting,
        ],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/preparation-orders/form-op",
        title: "Control",
        icon: "fas fa-shopping-cart",
        roles: [
          Permissions.PermissionsEnum.SuperAdmin,
          Permissions.PermissionsEnum.OrderPreparationControl,
        ],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/preparation-orders/controlled-op",
        title: "Listing Control",
        icon: "fas fa-shopping-cart",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/preparation-orders/archive-op",
        title: "Archive",
        icon: "fas fa-shopping-cart",
        roles: [
          Permissions.PermissionsEnum.SuperAdmin,
          Permissions.PermissionsEnum.OrderPreparationArchive,
        ],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/preparation-orders/consolidation-op",
        title: "Consolidation",
        icon: "fas fa-shopping-cart",
        roles: [
          Permissions.PermissionsEnum.SuperAdmin,
          Permissions.PermissionsEnum.OrderPreparationConsolidation,
        ],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/preparation-orders/expedition-op",
        title: "Expedition",
        icon: "fas fa-shopping-cart",
        roles: [
          Permissions.PermissionsEnum.SuperAdmin,
          Permissions.PermissionsEnum.OrderPreparationExpedition,
        ],
        class: "ml-menu",
        submenu: [],
      },
      // {
      //   path: "/preparation-orders/orders-for-agent",
      //   title: "Commandes validées",
      //   icon: "fas fa-shopping-cart",
      //   roles: [
      //    Permissions.PermissionsEnum.SuperAdmin,
      //    Permissions.PermissionsEnum.OrderPreparationControl,
      //   ],
      //   class: "ml-menu",
      //   submenu: [],
      // },
      {
        path: "/preparation-orders/deleivery-orders",
        title: "Bons de livraison",
        icon: "fas fa-shopping-cart",
        roles: [Permissions.PermissionsEnum.SuperAdmin],
        class: "ml-menu",
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Reporting",
    icon: "fas fa-file",
    class: "menu-toggle",
    roles: [
      Permissions.PermissionsEnum.SuperAdmin,
      Permissions.PermissionsEnum.ReportingView,
    ],
    submenu: [
      {
        path: "/reporting/detail-product-list",
        title: "Journal des ventes",
        icon: "fas fa-shopping-cart",
        roles: [
          Permissions.PermissionsEnum.SuperAdmin,
          //Permissions.PermissionsEnum.ReportingView,
        ],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/reporting/all-reserved-qnt",
        title: "Quantités reservées",
        icon: "fas fa-shopping-cart",
        roles: [
          Permissions.PermissionsEnum.SuperAdmin,
          //Permissions.PermissionsEnum.ReportingView,
        ],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/reporting/turnover-customers",
        title: "Chiffre d'affaires",
        icon: "fas fa-shopping-cart",
        roles: [Permissions.PermissionsEnum.SuperAdmin, 
          Permissions.PermissionsEnum.ReportingView,],
        class: "ml-menu",
        submenu: [],
      },
      {
        path: "/reporting/all-debt-list",
        title: "Créances",
        icon: "fas fa-shopping-cart",
        roles: [Permissions.PermissionsEnum.SuperAdmin, 
          Permissions.PermissionsEnum.ReportingView,],
        class: "ml-menu",
        submenu: [],
      },
    ],
  },
];
